export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <head>
      </head>
      <body>
        <header>this is header</header>

        <div>{children}</div>

        <footer>this is footer2</footer>
      </body>
    </html>
  )
}
